package objects;

/**
 * This class is a Java record and represents an email message.
 * Using this record allows creation a {@link Message} object using {@link MessageBuilder}
 */
public record Message(String sender, String recipient, String subject, String content) {
}    // No need for additional methods or constructors, as they are automatically generated by the record.

// Java record, introduced in Java 16, providing a concise way to create immutable data-carrying classes without the need for explicit boilerplate code.
// Below how class looked before converting to record.
// -------------------------------------------
//    private final String sender;
//    private final String recipient;
//    private final String subject;
//    private final String content;
//
//    public Message(String sender, String recipient, String subject, String content) {
//        this.sender = sender;
//        this.recipient = recipient;
//        this.subject = subject;
//        this.content = content;
//    }
//
//    public String getSender() {
//        return sender;
//    }
//
//    public String getRecipient() {
//        return recipient;
//    }
//
//    public String getSubject() {
//        return subject;
//    }
//
//    public String getContent() {
//        return content;
//    }
